services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  korvet:
    image: redisfield/korvet:latest
    ports:
      - "9092:9092"
      - "8080:8080"
    mem_limit: 2g
    environment:
      - KORVET_REDIS_HOST=redis
      - KORVET_REDIS_PORT=6379
      - SERVER_PORT=8080
      - KORVET_SERVER_PORT=9092
      - KORVET_REDIS_METRICS_ENABLED=true
      - KORVET_REDIS_METRICS_HISTOGRAM=true
      - BPL_JVM_THREAD_COUNT=250
      - JAVA_TOOL_OPTIONS=-XX:MaxDirectMemorySize=512m
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - korvet

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./grafana-dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml:ro
      - ./dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus

  kafka-tools:
    image: confluentinc/cp-kafka:7.8.0
    command: sleep infinity
    depends_on:
      - korvet
