include:
  - ../../observability/docker-compose.yml

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  korvet:
    image: redisfield/korvet:early-access
    ports:
      - "9092:9092"
      - "8080:8080"
    mem_limit: 2g
    environment:
      - KORVET_REDIS_HOST=redis
      - KORVET_REDIS_PORT=6379
      - SERVER_PORT=8080
      - KORVET_SERVER_PORT=9092
      - KORVET_REDIS_METRICS_ENABLED=true
      - KORVET_REDIS_METRICS_HISTOGRAM=true
      - BPL_JVM_THREAD_COUNT=50
      - JAVA_TOOL_OPTIONS=-XX:MaxDirectMemorySize=512m
    depends_on:
      - redis

  kafka-tools:
    image: confluentinc/cp-kafka:7.8.0
    command: sleep infinity
    depends_on:
      - korvet
