global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'korvet'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['korvet:8080']
        labels:
          application: 'korvet'
          environment: 'load-testing'
