apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: korvet-benchmark

resources:
  - ../../base

# 1 producer (default)
patches:
  - target:
      kind: Job
      name: benchmark-producer
    patch: |-
      - op: replace
        path: /spec/parallelism
        value: 1
      - op: replace
        path: /spec/completions
        value: 1

labels:
  - pairs:
      benchmark.korvet.io/dimension: producers
      benchmark.korvet.io/value: "1"

