# Kustomization for Korvet Flink Cold Storage Writer
# 
# Deploy with Flink Operator:
#   kubectl apply -k korvet-flink/k8s
#
# Deploy as standalone job (edit kustomization to comment out flink-application.yaml):
#   kubectl apply -k korvet-flink/k8s
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: korvet

resources:
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  # Choose ONE of the following deployment methods:
  - flink-application.yaml  # For Flink Kubernetes Operator
  # - job.yaml               # For standalone Kubernetes Job

commonLabels:
  app.kubernetes.io/name: korvet-flink
  app.kubernetes.io/component: cold-storage-writer
  app.kubernetes.io/part-of: korvet

images:
  - name: redisfield/korvet-flink
    newTag: latest

